# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: curl-test-check
        name: Check if curl commands are tested
        entry: bash pre_commit_check.sh
        language: system
        pass_filenames: false